In [2]:
import numpy as np

my_array = np.arange(25).reshape(5,5)
my_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
my_array[:2, 1:4]

array([[1, 2, 3],
       [6, 7, 8]])

In [27]:
my_array[[0,2],[1,2]]

array([ 1, 12])

In [23]:
my_array[1][0:2]

array([5, 6])

In [28]:
my_array[0,1]

1

In [30]:
my_array[(0,1),]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])